export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DETAIL = 'SET_USER_DETAIL';
export const SET_CHACHED_DATA = 'SET_CHACHED_DATA';
export const GET_CHACHED_DATA = 'GET_CHACHED_DATA';
export const CHANGE_NAT = 'CHANGE_NAT';